# Watch directory where microscope saves files
watch_directory: "E:/globus_data"

# Log files configuration
log_file: "logs/processed_files.json"

# DataFed configuration
datafed:
  repo_id: "p/test-automation"  # Replace with your actual DataFed repository ID
  parent_collection: "root"
  default_tags: ["microscope", "volume"]

# Logging configuration
logging:
  level: "DEBUG"  # Log level for files
  console_level: "INFO"  # Log level for console
  file: "logs/diatoms_to_datafed.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10MB
  backup_count: 5  # Keep 5 backup files
  capture_warnings: true 